version: "3.8"
services:
    web:
      build: .
      image: veeraphatamo/myapp:1.1.1
      ports:
        - "4000:4000"
    mongo:
      image: mongo:4.2.8
      environment: 
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=mydb